export const GEMINI_VOICES = [
    { id: 'en-US-Studio-O', name: 'Studio Voice O (Female)' },
    { id: 'en-US-Studio-M', name: 'Studio Voice M (Male)' },
    { id: 'en-US-Wavenet-A', name: 'WaveNet A (Female)' },
    { id: 'en-US-Wavenet-B', name: 'WaveNet B (Male)' },
    { id: 'en-US-Wavenet-C', name: 'WaveNet C (Female)' },
    { id: 'en-US-Wavenet-D', name: 'WaveNet D (Male)' },
    { id: 'en-US-Wavenet-E', name: 'WaveNet E (Female)' },
    { id: 'en-US-Wavenet-F', name: 'WaveNet F (Male)' },
    { id: 'en-US-Wavenet-G', name: 'WaveNet G (Female)' },
    { id: 'en-US-Wavenet-H', name: 'WaveNet H (Female)' },
    { id: 'en-US-Wavenet-I', name: 'WaveNet I (Male)' },
    { id: 'en-US-Wavenet-J', name: 'WaveNet J (Male)' },
    { id: 'en-US-News-K', name: 'News K (Female)' },
    { id: 'en-US-News-L', name: 'News L (Male)' },
    { id: 'en-US-News-M', name: 'News M (Male)' },
    { id: 'en-US-News-N', name: 'News N (Female)' },
    { id: 'en-GB-Wavenet-A', name: 'British WaveNet A (Female)' },
    { id: 'en-GB-Wavenet-B', name: 'British WaveNet B (Male)' },
    { id: 'en-GB-Wavenet-C', name: 'British WaveNet C (Female)' },
    { id: 'en-GB-Wavenet-D', name: 'British WaveNet D (Male)' },
    { id: 'en-GB-Wavenet-F', name: 'British WaveNet F (Female)' },
    { id: 'en-GB-News-G', name: 'British News G (Female)' },
    { id: 'en-GB-News-H', name: 'British News H (Male)' },
    { id: 'en-GB-News-I', name: 'British News I (Female)' },
    { id: 'en-GB-News-J', name: 'British News J (Male)' },
    { id: 'en-AU-Wavenet-A', name: 'Aussie WaveNet A (Female)' },
    { id: 'en-AU-Wavenet-B', name: 'Aussie WaveNet B (Male)' },
    { id: 'en-AU-Wavenet-C', name: 'Aussie WaveNet C (Female)' },
    { id: 'en-AU-Wavenet-D', name: 'Aussie WaveNet D (Male)' },
    { id: 'en-AU-News-E', name: 'Aussie News E (Female)' },
];
