export const GEMINI_VOICES = [
    // Male
    { id: 'zubenelgenubi', name: 'Zubenelgenubi - Casual, Male' },
    { id: 'gacrux', name: 'Gacrux - Mature, Female' },
    { id: 'iapetus', name: 'Iapetus - Clear, Male' },
    { id: 'autonoe', name: 'Autonoe - Bright, Female' },
    { id: 'orus', name: 'Orus - Firm, Male' },
    { id: 'puck', name: 'Puck - Upbeat, Male' },
    { id: 'achernar', name: 'Achernar - Soft, Male' },
    { id: 'alnilam', name: 'Alnilam - Firm, Male' },
    { id: 'fenrir', name: 'Fenrir - Excitable, Male' },
    { id: 'charon', name: 'Charon - Informative, Male' },
    // Female
    { id: 'zephyr', name: 'Zephyr - Bright, Female' },
    { id: 'kore', name: 'Kore - Firm, Female' },
    { id: 'leda', name: 'Leda - Youthful, Female' },
    { id: 'aoede', name: 'Aoede - Breezy, Female' },
    { id: 'callirrhoe', name: 'Callirrhoe - Easy-going, Female' },
    { id: 'achird', name: 'Achird - Friendly, Female' },
    { id: 'algenib', name: 'Algenib - Gravelly, Male' },
    { id: 'despina', name: 'Despina - Smooth, Female' },
    { id: 'sulafat', name: 'Sulafat - Warm, Female' },
    { id: 'umbriel', name: 'Umbriel - Easy-going, Male' },
    // Default
    { id: 'rasalgethi', name: 'Rasalgethi - Informative, Male' },
    { id: 'enceladus', name: 'Enceladus - Breathy, Male' },
    { id: 'schedar', name: 'Schedar - Even, Male' },
    { id: 'sadaltager', name: 'Sadaltager - Knowledgeable, Male' },
    { id: 'vindemiatrix', name: 'Vindemiatrix - Gentle, Female' },
    { id: 'laomedeia', name: 'Laomedeia - Upbeat, Female' },
    { id: 'erinome', name: 'Erinome - Clear, Female' },
    { id: 'pulcherrima', name: 'Pulcherrima - Forward, Female' },
];

export const groupedVoices = {
    "Male": [
        { id: 'zubenelgenubi', name: 'Zubenelgenubi - Casual' },
        { id: 'gacrux', name: 'Gacrux - Confident' },
        { id: 'iapetus', name: 'Iapetus - Friendly' },
        { id: 'autonoe', name: 'Autonoe - Mature' },
        { id: 'orus', name: 'Orus - Thoughtful' },
        { id: 'puck', name: 'Puck - Clear' },
        { id: 'achernar', name: 'Achernar - Engaging' },
        { id: 'alnilam', name: 'Alnilam - Energetic' },
        { id: 'fenrir', name: 'Fenrir - Excitable' },
        { id: 'charon', name: 'Charon - Informative' },
    ],
    "Female": [
        { id: 'zephyr', name: 'Zephyr - Bright' },
        { id: 'kore', name: 'Kore - Youthful' },
        { id: 'leda', name: 'Leda - Professional' },
        { id: 'aoede', name: 'Aoede - Conversational' },
        { id: 'callirrhoe', name: 'Callirrhoe - Confident' },
        { id: 'achird', name: 'Achird - Youthful' },
        { id: 'algenib', name: 'Algenib - Warm' },
        { id: 'despina', name: 'Despina - Inviting' },
        { id: 'sulafat', name: 'Sulafat - Warm' },
        { id: 'umbriel', name: 'Umbriel - Easy-going' },
    ],
    "Default": [
        { id: 'rasalgethi', name: 'Rasalgethi - Informative' },
        { id: 'enceladus', name: 'Enceladus - Breathy' },
        { id: 'schedar', name: 'Schedar - Even' },
        { id: 'sadaltager', name: 'Sadaltager - Knowledgeable' },
        { id: 'vindemiatrix', name: 'Vindemiatrix - Gentle' },
        { id: 'laomedeia', name: 'Laomedeia - Upbeat' },
        { id: 'erinome', name: 'Erinome - Clear' },
        { id: 'pulcherrima', name: 'Pulcherrima - Forward' },
    ]
};
